### ISSUE TITLE
Spring vs Spring Boot

### ISSUE THREAD

**Issue by chance0523** [chance0523/Techo-Talk-Study#4]
# Spring vs Spring Boot
- [해당 영상의 레포](https://github.com/samuel950523/Techo-Talk-Study/tree/main/%EC%A3%BC%EC%A0%9C%EB%93%A4/Process%26Thread)

### 완료 댓글을 달아주세요
- 댓글에 본인이 작성한 md나 블로그 글 링크를 첨부하셔도 됩니다.

**Comment by samuel950523** [comment]
해당 Issue는 탬플릿을 사용한 예시입니다!
여기에는 완료 댓글을 달지 말아주세요~
